# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs

jobs:
  print_greetings:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo HELLO
      - run: echo WORLD
      - run: echo $_env_name
  upload_file:
    docker:
      - image: alpine:latest
    steps:
      - run: echo "THIS IS A SAMPLE TEXT" > ~/output.txt  
      - persist_to_workspace:
          root: ~
          paths: 
            - output.txt  
  download_file:
    docker:
      - image: alpine:latest
    steps:
      - attach_workspace:
          at: ~
      - run: cat output.txt  

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - print_greetings
      - upload_file
      - download_file:
          requires:
            - upload_file